db:
  host: 'nest-js-5295.8nk.cockroachlabs.cloud'
  username: 'hiro'
  password: 'R_Z4ssy4hOAzHRXWB-6qNg'
  port: 26257
  database: 'taskmon_ai'
  ssl: true

server:
  port: 1607
#  origin: localhost

jwt:
  secret: 'secret123'
