#server:
#  origin: https://nextjs-task-mgmt.vercel.app/
#db:
#  synchronize: false
db:
  host: 'nest-js-5295.8nk.cockroachlabs.cloud'
  username: 'hiro'
  password: 'R_Z4ssy4hOAzHRXWB-6qNg'
  port: 26257
  database: 'taskmon_ai_test'
  ssl: true
  synchronize: false
