name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust the branch name as per your project setup
    paths:
      - '.github/workflows/deploy.yml'
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

env:
  VITE_BASE_URL: 'http' #TODO:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

defaults:
  run:
    working-directory: ${{ github.workspace }}/Frontend
    shell: bash
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Get npm cache
        id: npm-cache
        run: echo "NPM_CACHE_DIR=$(pwd)/node_modules" >> "${GITHUB_OUTPUT}"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache.outputs.NPM_CACHE_DIR }}
          key:
            npm-${{github.workflow}}-${{ runner.os }}-${{
            hashFiles('**package.json') }}
          restore-keys: |
            npm-${{github.workflow}}-${{ runner.os }}-${{ hashFiles('**package.json') }}

      - name: Install dependencies
        run: npm install --include=dev

      - name: Deploy to GitHub Pages
        uses: bitovi/github-actions-react-to-ghp@v1.2.0
        with:
          checkout: false
          # Specifies the path of the static assets after building
          path: ${{ github.workspace }}/Frontend/build
          # Specifies the command to run after npm ci for the build
          build_command: npm run build
