name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    tags:
      - '*'
      - '**'
    paths:
      - '.github/workflows/deploy.yml'
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

env:
  VITE_BASE_URL: 'http' #TODO:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

defaults:
  run:
    working-directory: ./Frontend
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: default
#      name: github-pages
#      url: ${{ steps.build-publish.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.6

      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 19
          check-latest: true

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.wkdir.outputs.wkdir }}/build
