name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    tags:
      - '*'
      - '**'
    paths:
      - '.github/workflows/deploy.yml'
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

env:
  VITE_BASE_URL: 'http' #TODO:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

defaults:
  run:
    working-directory: ./Frontend
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
#    environment:
#      name: github-pages
#      url: ${{ steps.build-publish.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Get npm cache
        id: npm-cache
        run: echo "NPM_CACHE_DIR=$(pwd)/node_modules" >> "${GITHUB_OUTPUT}"


      - name: Get working directory
        id: wkdir
        run: |
          echo "wkdir=$(pwd)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache.outputs.NPM_CACHE_DIR }}
          key:
            npm-${{github.workflow}}-${{ runner.os }}-${{ hashFiles('${{ steps.wkdir.outputs.wkdir }}/package.json') }}

          restore-keys: |
            npm-${{github.workflow}}-${{ runner.os }}-${{ hashFiles('${{ steps.wkdir.outputs.wkdir }}/package.json') }}

      - name: Install dependencies
        run: npm install --include=dev

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.wkdir.outputs.wkdir }}/build
