name: Deploy to Surge

on:
  push:
    branches:
      - main
    tags:
      - '*'
      - '**'
    paths:
      - '.github/workflows/deploy.yml'

  pull_request: #FIXME: remove after testing
    branches: [ "main" ]

  workflow_dispatch:

env:
  VITE_BASE_URL: 'http' #TODO:
  domain: taskmon.surge.sh

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./Frontend
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: surge


    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.6

      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 19
          check-latest: true

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Extract Domain
        id: extract_domain
        run: |
          ref=$(git rev-parse --abbrev-ref HEAD)
          sref=${ref//\//-}
          echo "preview_domain=$sref-$domain" >> $GITHUB_OUTPUT

      - name: Get working directory
        id: wkdir
        run: |
          echo "wkdir=$(pwd)" >> $GITHUB_OUTPUT

      - name: Preview to ${{ steps.extract_domain.outputs.preview_domain }}
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: ${{ steps.extract_domain.outputs.preview_domain }}
          project: ${{ steps.wkdir.outputs.wkdir }}/build
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}

      - name: Deploy to ${env.domain}
        if:
          ${{ startsWith(github.ref, 'refs/tags/') || github.ref ==
          'refs/heads/main' }}
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: ${env.domain}
          project: ${{ steps.wkdir.outputs.wkdir }}/build
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
